   version: '3.8'
   services:
     app:
       build:
         context: .
         dockerfile: Dockerfile
       working_dir: /app
       volumes:
         - .:/app
         - /app/node_modules
         # 不再使用 .next 的卷挂载
       ports:
         - "9000:9000"
       environment:
         - NODE_ENV=production
         - TZ=Asia/Shanghai
       # 使用最简单的构建和启动命令
       command: sh -c "npm run build && npm run start && node cron.mjs"
       restart: unless-stopped